// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `pkg-config`
func defaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "/x-tools/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-cc"
}
func defaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "/x-tools/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-c++"
}
