// Code generated by go tool dist; DO NOT EDIT.

package cfg

const DefaultPkgConfig = `pkg-config`
func DefaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "/x-tools/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-cc"
}
func DefaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "/x-tools/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-c++"
}
